In [1]:
import numpy as np

In [3]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
b=np.array(((1,2,3),(4,5,6)),dtype=float)
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [15]:
print(np.reshape(b,(3,2)))

[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [7]:
c=np.arange(2,20,2)
print(c)

[ 2  4  6  8 10 12 14 16 18]


In [11]:
c.reshape(3,3)
c.reshape(-1,9)
c.reshape(9,-1)

array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12],
       [14],
       [16],
       [18]])

In [13]:
print(np.reshape(c,(-1,9)))
print(np.reshape(c,(9,-1)))

[[ 2  4  6  8 10 12 14 16 18]]
[[ 2]
 [ 4]
 [ 6]
 [ 8]
 [10]
 [12]
 [14]
 [16]
 [18]]
